# This is a basic workflow to showcase the use of Reusable Workflows

name: secret sniffle

on:
  workflow_dispatch:

jobs:
  do-it:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Welcome to Baker Hughes!

  docker:
    uses: umangcypher-BH/sturdy-sniffle/.github/workflows/secret santa.yaml@master
    with:
      image_name: umangcypherbh/trviyscan2demo
      tag: umangcypherbh/trviyscan2demo
    secrets:
      registry_username: ${{secrets.REGISTRY_USERNAME}}
      registry_password: ${{secrets.REGISTRY_PASSWORD}}
