name: secret santa

on:
     push:
       branches:
        - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:

     - name: Checkout code
       uses: actions/checkout@v2
      
     - name: Docker Login
       uses: docker/login-action@v2
       with:          
          username: ${{ secrets.umangcypherbh }}
          password: ${{ secrets.Cypher@87 }} 
     - name: Build and push
       uses: docker/build-push-action@v3
       with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/trviyscan2demo:latestv1.0
